apiVersion: v1
kind: Secret
metadata:
  name: sonarqube-secret
  namespace: sonarqube
type: Opaque
data:
  # echo -n 'postgres' | base64
  SONARQUBE_JDBC_PASSWORD: cG9zdGdyZXM=
stringData:
  SONARQUBE_JDBC_URL: "jdbc:postgresql://postgres:5432/sonarqube"
  SONARQUBE_JDBC_USERNAME: sonarqube