apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube
  namespace: sonarqube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      containers:
        - name: sonarqube
          image: sonarqube:9.8.0-community
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 9000
          envFrom:
            - secretRef:
                name: sonarqube-secret
          volumeMounts:
            - name: sonarqube-data
              mountPath: "/opt/sonarqube/data/"
            - name: sonarqube-data
              mountPath: "/opt/sonarqube/extensions/"
      volumes:
        - name: sonarqube-data
          persistentVolumeClaim:
            claimName: pvc-sonarqube