apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-sonarqube
  namespace: sonarqube
spec:
  volumeName: pv-sonarqube
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi