apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-jenkins
  namespace: jenkins
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 2Gi
  hostPath:
    path: /workspace/jenkins