apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-postgres
  namespace: sonarqube
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  hostPath:
    path: /workspace/sonarqube/postgres