apiVersion: v1
kind: Service
metadata:
  name: adminer
  namespace: sonarqube
spec:
  type: ClusterIP
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: adminer
  sessionAffinity: None