kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: skywalker
nodes:
- role: control-plane
  extraMounts:
    - hostPath: ./volumes/control-plane
      containerPath: /workspace
- role: worker
  extraMounts:
    - hostPath: ./volumes/worker
      containerPath: /workspace
- role: worker
  extraMounts:
    - hostPath: ./volumes/worker
      containerPath: /workspace
- role: worker
  extraMounts:
    - hostPath: ./volumes/worker
      containerPath: /workspace