apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-postgres
  namespace: sonarqube
spec:
  volumeName: pv-postgres
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi