apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: sonarqube
type: Opaque
data:
  # echo -n 'postgresql' | base64
  POSTGRES_ADMIN_PASSWORD: cG9zdGdyZXNxbA==
  # echo -n 'postgres' | base64
  POSTGRES_PASSWORD: cG9zdGdyZXM=
stringData:
  POSTGRES_DATABASE: sonarqube
  POSTGRES_USER: sonarqube
  PGDATA: /var/lib/postgresql/data