apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-jenkins-worker
  namespace: common-cicd
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 2Gi
  hostPath:
    path: /workspace/jenkins/worker