apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-jenkins-worker
  namespace: common-cicd
spec:
  volumeName: pv-jenkins-worker
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi