apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    name: nginx
spec:
  restartPolicy: Always
  volumes:
    - name: data
      emptyDir: {}
  initContainers:
    - name: nginx-init
      image: docker/whalesay
      command: [sh, -c]
      args: [echo "<pre>$(cowsay -b 'Hello Kubernetes')</pre>" > /data/index.html]
      volumeMounts:
        - mountPath: /data
          name: data
  containers:
  - name: nginx
    image: nginx:1.11
    volumeMounts:
      - mountPath: /usr/share/nginx/html
        name: data
